Repository csivitu/WebDice, pull requests merged in 2022-10, with the labels that each got.

#17 Total number of Dad laughs added #2
  Daddy-Laugh/index.html
Labels: hacktoberfestapproved

#38 Find total number of dads visited #3
  Daddy-Laugh/index.html
Labels: hacktoberfest-approved

#40 Find total number of dad laughs played altogether on the platform #5
  Daddy-Laugh/index.html
Labels: hacktoberfest-approved

#51 Update README.md
  README.md
Labels: hacktoberfest
